### ISSUE TITLE
Re-use example

### ISSUE THREAD

**Issue by kheinzz** [IGNF/FLAIR-1#16]
Hi,

Thank you for your work and making it available.

Would it be possible to provide an example of how to perform inference using the model you provided on an image? I imagine a common use case would be applying the Cosia model to older BD_ortho images. Providing a detailed example on Google Colab could make the process much more accessible.

By advance thanks for your answer !

**Comment by agarioud** [comment]
Dear @kheinzz ,

Thank you for your feedback. I note the interest in a notebook, but we are currently working on a new version of the code, and this is not possible in the short term.

To perform an inference, you need to use the flair-detect module by pointing to the image of your choice (from the BD Ortho) and to the model downloaded, for example, from the HF page (https://huggingface.co/collections/IGNF/flair-models-landcover-semantic-segmentation-65bb67415a5dbabc819a95de).

The README details the arguments to be given to the ```flair-1-config-detect.yaml``` configuration file.

If, for example, you use this model: https://huggingface.co/IGNF/FLAIR-INC_rgbie_15cl_resnet34-unet
the configuration file would be, for example:


```
output_path: whatever
output_name: whatever

input_img_path:  ../path/to/raster/file.tif
channels: [1, 2, 3, 4, 5]

img_pixels_detection: 512
margin: 128
output_type: "argmax"
n_classes: 19


model_weights: ../path/to/model/weights/FLAIR-INC_rgbie_15cl_resnet34-unet_weights.pth
model_framework: 
    model_provider: SegmentationModelsPytorch
    
    HuggingFace:
        org_model: 
    SegmentationModelsPytorch:
        encoder_decoder: resnet34_unet


batch_size: 4
use_gpu: true
num_worker: 2

write_dataframe: False

norma_task: 
  - norm_type: custom 
    norm_means: [105.08, 110.87, 101.82, 106.38, 53.26]
    norm_stds: [52.17, 45.38, 44, 39.69, 79.3]
```

the you would call 
```
flair-detect --conf=path/to/flair-1-config-detect.yaml
```
