### ISSUE TITLE
Error from Rasterio TypeError: self._hds cannot be converted to a Python object for pickling

### ISSUE THREAD

**Issue by NickBear-star** [IGNF/FLAIR-1#19]
Hello, 

When running the zone_detect example, I get the following error message:
```
...
  File "<stringsource>", line 2, in rasterio._io.DatasetReaderBase.__reduce_cython__
TypeError: self._hds cannot be converted to a Python object for pickling
```

The error originates from the following line in `src/zone_detect/main.py`:
```
for samples in tqdm(data_loader):
```

The error is related to this issue: https://github.com/dymaxionlabs/dask-rasterio/issues/3
As far as I understand, Rasterio datasets can't be pickled and can't be shared between processes or threads.

My env on Windows 10:
```
Package                     Version
--------------------------- -----------
Python                      3.12.8
geopandas                   1.0.1
huggingface-hub             0.27.1
imageio                     2.37.0
jsonargparse                4.36.0
lazy-loader                 0.4
lightning-utilities         0.11.9
mpmath                      1.3.0
omegaconf                   2.3.0
pillow                      11.1.0
pretrainedmodels            0.7.4
pytorch-lightning           2.5.0.post0
rasterio                    1.4.3
scikit-image                0.25.1
segmentation-models-pytorch 0.4.0
torch                       2.5.1
torchmetrics                1.6.1
torchvision                 0.20.1
transformers                4.48.1
```

My config:
```
output_path: /tmp/test_flair
output_name: test

input_img_path: /tmp/test_flair/input.tif
channels: [1, 2, 3]

img_pixels_detection: 512
margin: 128
output_type: "argmax"
n_classes: 19


model_weights: /src/hugging-face/FLAIR-INC_rgb_15cl_resnet34-unet_weights.pth 
model_framework: 
    model_provider: SegmentationModelsPytorch
    
    HuggingFace:
        org_model: openmmlab/upernet-swin-small
    SegmentationModelsPytorch:
        encoder_decoder: resnet34_unet


batch_size: 4
use_gpu: false
num_worker: 2

write_dataframe: False

norma_task: 
  - norm_type: scaling
    norm_means: [105.08, 110.87, 101.82, 106.38, 53.26]
    norm_stds: [52.17, 45.38, 44, 39.69, 79.3]
```
